### ISSUE TITLE
random string benckmark will be better indicator of speed

### ISSUE THREAD

**Issue by wangyi-fudan** [avaneev/komihash#1] opened 2021-12-03 10:28 UTC
Hi,
  I benchmark komihash with my benckmark suite: 
 https://github.com/wangyi-fudan/wyhash/blob/master/benchmark.cpp

It seems that random string hash has a big gap using gcc 9.3 and ubuntu 20.04 @ 11th generation i3

/usr/share/dict/words
|hash function	|short hash/us	|bulk_256B GB/s	|bulk_64KB GB/s	|
|----		|----		|----		|----		|
|wyhash		|460.71		|23.90		|28.74		|
|komihash		|104.08		|15.82		|23.16		|

**Comment by avaneev** [comment] 2021-12-03 12:11
Thanks. I can only partially confirm your finding. My similar benchmark that uses 216000 words shows that komihash's throughput is only 2x slower. On the `dict` file you are using it's 3x slower, by no means 4.6x slower. Please see these PDF plots of word lengths for two sets, yours and mine. As you can see, PDFs are mostly similar while speed differences are tremendous. The understandable reason for this is that komihash at 7 symbols at average has larger overhead due to overlap-less message parsing. But in my wordset the average is at 9 symbols, thus showing a closer performance to wyhash. The problem is in "resonance". At some particular wordlengths wyhash is faster, but on equidistributed lengthes they are mostly equal.

I repeat word randomization 64 times, and use this inner loop, I use `v ^= msg[ 0 ];` to measure overhead. If I do not subtract overhead, the difference between wyhash and komihash is much smaller.

```
		const TClock t1( CSystem :: getClock() );

		volatile uint64_t sd = k + 1;

		for( int i = 0; i < StringList.getItemCount(); i++ )
		{
			volatile size_t msgl = StringList[ i ].getLength();
			volatile const uint8_t* msg = StringList[ i ].getASCIIData();

			v ^= komihash( (void*) msg, msgl, sd );
//			v ^= wyhash( (uint8_t*) &msg, msgl, sd, _wyp );
//			v ^= msg[ 0 ];
		}

		td += CSystem :: getClockDiffSec( t1 );
```

![pdf_words](https://user-images.githubusercontent.com/11453377/144599413-3fedb1a0-7b93-40eb-bc8f-b9822dc50b29.png)
![pdf_english](https://user-images.githubusercontent.com/11453377/144599420-a4eeb8b1-d33e-4600-973a-91f52fa5501b.png)

**Comment by avaneev** [comment] 2021-12-03 12:23
I would add that in this particular "word hashing" case, komihash's throughput is much lower. But noone can tell which statistics there will be in a particular hash-table/hash-map, in a particular project. So, in some "average use case", wyhash and komihash are comparable.

**Comment by avaneev** [comment] 2021-12-03 12:46
Also consider `cycl./map` at https://github.com/rurban/smhasher - wyhash has 196.77 while komihash has 180.99. It's an example of a use-case when a seeming advantage of wyhash flips to disadvantage.

**Comment by avaneev** [comment] 2021-12-03 12:54
As for the overhead, you can't get around it as you have to fetch message's address and length. So, practical difference in this rather "specific" test that does not account for word repetition statistics, is about 1.8x.

**Comment by avaneev** [comment] 2021-12-03 17:31
@wangyi-fudan You may try komihash 2.8.12, it should be slightly faster with GCC on Intel (I assume you have an Intel processor since komihash bulk performance is much lower than wyhash's). But AMD Zen2-3 is now a new strong player, you also have to optimize for it.

**Comment by avaneev** [comment] 2021-12-03 18:35
I've updated estimates, they are closer to your estimates now, but still not 4.6x...

**Comment by avaneev** [comment] 2021-12-04 00:25
@wangyi-fudan By the way, consider running such test... I see you worry about throughput on random lengthes, like it matters a lot. However, in such test, komirand is quite a bit ahead of wyhash, at least on Ryzen 3700X. So, wyrand is likely not "branch-predictor-friendly".

```
	const uint64_t rc = 1ULL << 26;
	const int minl = 8; const int maxl = 28;
	const int lc = ( maxl - minl + 1 );
	volatile size_t msg[ 16 ] = { 0 };
	uint64_t Seed1 = 1, Seed2 = Seed1;
	uint64_t v = 0;

	const TClock t1( CSystem :: getClock() );

	for( int k = 0; k < lc; k++ )
	{
		volatile size_t msgl = minl + komirand( &Seed1, &Seed2 ) % lc;
		volatile uint64_t sd = k;

		for( uint64_t i = 0; i < rc; i++ )
		{
			v ^= komihash( (uint8_t*) &msg, msgl, sd );
//			v ^= wyhash( (uint8_t*) &msg, msgl, sd, _wyp );
//			v ^= msg[ 0 ] ^ msgl;
			msg[ 0 ]++;
		}
	}

	printf( "%016llx\n", v );
	printf( "%.1f\n", CSystem :: getClockDiffSec( t1 ) * 4.2e9 / ( rc * lc ));
```

**Comment by avaneev** [comment] 2021-12-04 01:48
Here's a self-explanatory plot of throughputs (overhead excluded) of wyhash and komihash for len=0...15. At len=7 the difference is biggest. If you run this test on some other stringset, with e.g. mean=10, wyhash may even come last.
![_throughput](https://user-images.githubusercontent.com/11453377/144692408-eb9bc58a-615a-4979-b487-1b0eadb9373d.png)

**Comment by avaneev** [comment] 2021-12-04 02:28
Well, after more testing and measurements I admit that on uniformly random lengths komihash has a pretty large overhead. I do not quite understand where it comes from, because "raw", repeating, measurements show a different picture. As I've measured, it comes from the `kh_lpu64ec()` function which is exactly the "overlap-less" parsing part. I will be trying to understand why that happens and how to fix this. Thanks for pointing me out to this benchmarking method. But I think uniformly-random message length hashing is not a realistic scenario.

**Comment by avaneev** [comment] 2021-12-04 04:17
OK, yes, the culprit is the `kh_lpu64ec()` function which does the "overlap-less" parsing. It's about 29 cycles/h overhead compared to wyhash, and it's fixed, independent of message's length. Unfixable, unfortunately. I'm now working on improving it, but so far improvement is small. Anyway, we are talking about a "worst-case scenario" when message lengths are random, and make processor's branch predictor go awry. As I've tested, in various other scenarios the difference between komihash and wyhash is minimal. Then there's a factor of "hash quality" which drives the construction and access of hash-map, for example. This is too complex to measure.

komihash was initially "quality" over "quantity". Programmers will decide what's better to them. I think it's quite wise to have several good hash functions at one's disposal and use whatever works best in a given use case.

**Comment by avaneev** [comment] 2021-12-04 11:10
@wangyi-fudan Please retest komihash 3.0, I've did my best for this benchmark. komihash is now quite close to XXH3_64 in this test. So, best of both worlds now.

**Comment by avaneev** [comment] 2021-12-06 04:29
@wangyi-fudan You may retest komihash 3.4 now.

**Closed** 2021-12-06 21:57 UTC
